#route:
 #   receiver: 'slack'

#receivers:
 #   - name: 'slack'
  #    slack_configs:
   #       - send_resolved: true
#            username: '<username>'
 #           channel: '#<channel-name>'
  #          api_url: '<incomming-webhook-url>'
global:

templates:
- '/etc/alertmanager/*.tmpl'
# The root route on which each incoming alert enters.
route:
  # default route if none match
  receiver: alert-emailer

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  # TODO:
  group_by: ['alertname', 'priority']

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

receivers:
- name: alert-emailer
  email_configs:
  - to: 'gohilamariappan@gmail.com'
    from: 'gohilamariappan@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'gohilamariappan@gmail.com'
    auth_password: 'password'
    auth_secret: 'gohilamariappan@gmail.com'
    auth_identity: 'gohilamariappan@gmail.com'
