#route:
 #   receiver: 'slack'

#receivers:
 #   - name: 'slack'
  #    slack_configs:
   #       - send_resolved: true
#            username: '<username>'
 #           channel: '#<channel-name>'
  #          api_url: '<incomming-webhook-url>'
global:
  smtp_require_tls: false
templates:
- '/etc/alertmanager/*.tmpl'
# The root route on which each incoming alert enters.
route:
  # default route if none match
  receiver: alert-emailer

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  # TODO:
  group_by: ['alertname', 'priority']

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.

receivers:
- name: alert-emailer
  email_configs:
  - to: 'sivaprakash.ramasamy@tarento.com'
    from: 'no-reply@tarento.com'
    smarthost: 'smtpout.idc.tarento.com:25'
    auth_username: ''
    auth_password: ''
    auth_secret: ''
    auth_identity: ''
