global:
 # scrape_interval:     10s
 # evaluation_interval: 10s
#  scrape_timeout: 10s


scrape_configs:
  # Scrape Prometheus itself every 10 seconds.
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
     - targets:
          - 'prometheus:9090'

  - job_name: 'cadvisor'
    scrape_interval: 10s
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  
  - job_name: 'node-exporter'
    scrape_interval: 10s
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'anuvaad'
    scrape_interval: 10s
    static_configs:
     - targets:
          - 'gateway_anuvaad-corpus-node:9091'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
     - targets:
          - 'prom_alertmanager:9093'

