global:
 # scrape_interval:     10s
 # evaluation_interval: 10s
#  scrape_timeout: 10s


scrape_configs:
  # Scrape Prometheus itself every 10 seconds.
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
     - targets:
          - 'prom_prometheus:9090'

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
     - targets:
          - 'prom_cadvisor:8080'
  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
     - targets:
          - 'prom_node-exporter:9100'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
     - targets:
          - 'prom_alertmanager:9093'

